apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-dns
  namespace: external-dns
  releaseName: external-dns
  repo: external-dns
  valuesFile: values.yaml


resources:
- configs/config.yaml
- configs/ddns-cron.yaml
