apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metrics-server
  namespace: metrics-server
  releaseName: metrics-server
  repo: metrics-server
  valuesFile: values.yaml