apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: external-secrets
  releaseName: external-secrets
  namespace: external-secrets
  repo: external-secrets
  valuesFile: values.yaml

resources:
- bitwarden/bitwarden-cli-sealed-secret.yaml
- bitwarden/deployment.yaml
- bitwarden/example-secret.yaml
- bitwarden/secret-stores.yaml
