apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: metallb
  namespace: metallb-system
  releaseName: metallb
  repo: metallb
  valuesFile: values.yaml

resources:
- configs/configs.yaml