annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
apiVersion: v2
appVersion: 2.00.18
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
description: Tdarr is a self hosted web-app for automating media library transcode/remux
  management and making sure your files are exactly how you need them to be in terms
  of codecs/streams/containers etc.
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/tdarr
icon: https://s7.gifyu.com/images/GifCroppedTran.gif
keywords:
- transcoding
- remux
- media
- video
maintainers:
- email: k8s-at-home@xpander.eml.cc
  name: auricom
name: tdarr
sources:
- https://www.github.com/HaveAGitGat/Tdarr
- https://hub.docker.com/r/haveagitgat/tdarr/
- https://tdarr.io/docs/
version: 4.5.2
