domain: burrell.tech home.burrell.tech k8s.burrell.tech
service:
  annotations:
    metallb.universe.tf/address-pool: bgp-pool
    metallb.io/allow-shared-ip: "key-to-share-172.19.0.1"
  loadBalancerIP: 172.19.0.1
fallthrough:
  enabled: true
  zones:
    - burrell.tech