apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    external-dns.alpha.kubernetes.io/exclude: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/whitelist-source-range: 192.168.0.0/16,172.16.0.0/12
  name: shinobi
spec:
  rules:
    - host: shinobi.home.burrell.tech
      http:
        paths:
          - backend:
              service:
                name: shinobi
                port:
                  number: 8080
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - shinobi.home.burrell.tech
      secretName: shinobi.home.burrell.tech