apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shinobi-secrets
spec:
  target:
    name: shinobi-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        conf.json: |-
          {{ .conf }}
        super.json: |-
          {{ .super }}
        DB_USER: "{{ .DB_USER }}"
        DB_PASS: "{{ .DB_PASS }}"
  data:
    - secretKey: conf
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: conf
    - secretKey: super
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: super
    - secretKey: DB_USER
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: DB_USER
    - secretKey: DB_PASS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: DB_PASS

---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shinobi-pullsecret
spec:
  target:
    name: shinobi-pullsecret
    deletionPolicy: Delete
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
  data:
    - secretKey: dockerconfigjson
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: pullsecret