apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shinobi-secrets
spec:
  target:
    name: shinobi-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        config.json: |-
          {{ .config }}
        super.json: |-
          {{ .super }}
  data:
    - secretKey: config
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: c166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: config
    - secretKey: super
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: 166d9a9b-a580-41d4-aaf5-b3d7012d107b
        property: super