apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  repo: cert-manager
  namespace: cert-manager
  valuesFile: values.yaml

resources:
  - configs/*.yaml