apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: cert-manager
  namespace: cert-manager
  repo: cert-manager
  valuesFile: values.yaml

resources:
- configs/cloudflare-api-token-secret-private.yaml
- configs/cloudflare-api-token-secret.yaml
- configs/letsencrypt.yaml
- configs/selfsigned.yaml
