apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-secrets
spec:
  target:
    name: smtp-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        SMTP_RELAY_HOST: "{{ .SMTP_RELAY_HOST }}"
        SMTP_RELAY_MYHOSTNAME: "{{ .SMTP_RELAY_MYHOSTNAME }}"
        SMTP_RELAY_MYNETWORKS: "{{ .SMTP_RELAY_MYNETWORKS }}"
        SMTP_RELAY_USERNAME: "{{ .SMTP_RELAY_USERNAME }}"
        SMTP_RELAY_PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
        SMTP_RELAY_WRAPPERMODE: "{{ .SMTP_RELAY_WRAPPERMODE }}"
        SMTP_TLS_SECURITY_LEVEL: "{{ .SMTP_TLS_SECURITY_LEVEL }}"
        SMTP_MESSAGE_SIZE_LIMIT: "{{ .SMTP_MESSAGE_SIZE_LIMIT }}"
  data:
    - secretKey: SMTP_RELAY_HOST
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_HOST
    - secretKey: SMTP_RELAY_MYHOSTNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_MYHOSTNAME
    - secretKey: SMTP_RELAY_MYNETWORKS
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_MYNETWORKS
    - secretKey: SMTP_RELAY_USERNAME
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_USERNAME
    - secretKey: SMTP_RELAY_PASSWORD
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_PASSWORD
    - secretKey: SMTP_RELAY_WRAPPERMODE
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_RELAY_WRAPPERMODE
    - secretKey: SMTP_TLS_SECURITY_LEVEL
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_TLS_SECURITY_LEVEL
    - secretKey: SMTP_MESSAGE_SIZE_LIMIT
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: bb105431-ec6f-4ff6-8a97-b3df01255dad
        property: SMTP_MESSAGE_SIZE_LIMIT