annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Updated image to v1.7.1.
apiVersion: v2
appVersion: 1.7.1
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.16.2
- condition: redis.enabled
  name: redis
  repository: https://charts.bitnami.com/bitnami
  version: 15.7.6
description: Paperless - Index and archive all of your scanned paper documents
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/paperless
icon: https://avatars.githubusercontent.com/u/47271576?s=200&v=4
keywords:
- paperless
kubeVersion: '>=1.16.0-0'
maintainers:
- name: mr-onion-2
- email: jonathan@jonnobrow.co.uk
  name: jonnobrow
- email: charts@mor.re
  name: morremeyer
name: paperless
sources:
- https://github.com/paperless-ngx/paperless-ngx
version: 8.8.3
