annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
apiVersion: v2
appVersion: 8.0.7
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
- condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 10.5.1
description: seafile helm package
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/seafile
icon: https://manual.seafile.com/media/seafile-transparent-1024.png
keywords:
- seafile
kubeVersion: '>=1.16.0-0'
maintainers:
- email: 1985132+phybros@users.noreply.github.com
  name: phybros
name: seafile
sources:
- https://github.com/haiwen/seafile-docker
version: 2.2.2
