annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Upgraded `common` chart dependency to version 4.4.2
apiVersion: v2
appVersion: v4.1.0.6175
dependencies:
- name: common
  repository: https://library-charts.k8s-at-home.com
  version: 4.4.2
description: A fork of Sonarr to work with movies Ã  la Couchpotato
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/radarr
icon: https://github.com/Radarr/Radarr/blob/aphrodite/Logo/512.png?raw=true
keywords:
- radarr
- torrent
- usenet
kubeVersion: '>=1.16.0-0'
maintainers:
- email: jeff@billimek.com
  name: billimek
name: radarr
sources:
- https://github.com/Radarr/Radarr
- https://github.com/k8s-at-home/container-images
version: 16.2.3
